## Dự đoán bệnh từ các triệu chứng Đối với dự án này, chúng tôi sẽ sử dụng tập dữ liệu từ đây:
 http://people.dbmi.columbia.edu/~friedma/Projects/DiseaseSymptomKB/index.html

 Sao chép dữ liệu từ tất cả các cột và dán vào bảng tính excel -> `raw_data.xlsx

In [1]:
# Nhập các thư viện cần thiết
import csv
import pandas as pd
import numpy as np
from collections import defaultdict
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Kết nối Google Driv
# Đọc dữ liệu thô từ file Excel
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
# Read Raw Dataset
df = pd.read_excel('/content/drive/My Drive/Colab Notebooks/Check-check-test-test/dataset/raw_data.xlsx')

In [7]:
df.head(30)

Disease  \
0                  UMLS:C0020538_hypertensive disease   
1                                                 NaN   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
5                                                 NaN   
6                                                 NaN   
7                                                 NaN   
8                                                 NaN   
9                                                 NaN   
10                                                NaN   
11                                                NaN   
12                             UMLS:C0011847_diabetes   
13                                                NaN   
14                                                NaN   
15                                                NaN   
16                                                NaN   
17                                                NaN   
18                                                NaN   
19                                                NaN   
20                                                NaN   
21                                                NaN   
22                                                NaN   
23                                                NaN   
24                                                NaN   
25                                                NaN   
26  UMLS:C0011570_depression mental^UMLS:C0011581_...   
27                                                NaN   
28                                                NaN   
29                                                NaN   

    Count of Disease Occurrence  \
0                        3363.0   
1                           NaN   
2                           NaN   
3                           NaN   
4                           NaN   
5                           NaN   
6                           NaN   
7                           NaN   
8                           NaN   
9                           NaN   
10                          NaN   
11                          NaN   
12                       1421.0   
13                          NaN   
14                          NaN   
15                          NaN   
16                          NaN   
17                          NaN   
18                          NaN   
19                          NaN   
20                          NaN   
21                          NaN   
22                          NaN   
23                          NaN   
24                          NaN   
25                          NaN   
26                       1337.0   
27                          NaN   
28                          NaN   
29                          NaN   

                                              Symptom  
0                            UMLS:C0008031_pain chest  
1                   UMLS:C0392680_shortness of breath  
2                             UMLS:C0012833_dizziness  
3                              UMLS:C0004093_asthenia  
4                                  UMLS:C0085639_fall  
5                               UMLS:C0039070_syncope  
6                               UMLS:C0042571_vertigo  
7   UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...  
8                           UMLS:C0030252_palpitation  
9                                UMLS:C0027497_nausea  
10                      UMLS:C0002962_angina pectoris  
11                       UMLS:C0438716_pressure chest  
12                             UMLS:C0032617_polyuria  
13                           UMLS:C0085602_polydypsia  
14                  UMLS:C0392680_shortness of breath  
15                           UMLS:C0008031_pain chest  
16                             UMLS:C0004093_asthenia  
17                               UMLS:C0027497_nausea  
18                            UMLS:C0085619_orthopnea  
19                                 UMLS:C0034642_rale  
20  UMLS:C003899

In [8]:
# Điền các giá trị NaN bằng giá trị phía trên
data = df.fillna(method='ffill')

<ipython-input-8-73b9652b1c08>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = df.fillna(method='ffill')


In [9]:
data.head(30)

Disease  \
0                  UMLS:C0020538_hypertensive disease   
1                  UMLS:C0020538_hypertensive disease   
2                  UMLS:C0020538_hypertensive disease   
3                  UMLS:C0020538_hypertensive disease   
4                  UMLS:C0020538_hypertensive disease   
5                  UMLS:C0020538_hypertensive disease   
6                  UMLS:C0020538_hypertensive disease   
7                  UMLS:C0020538_hypertensive disease   
8                  UMLS:C0020538_hypertensive disease   
9                  UMLS:C0020538_hypertensive disease   
10                 UMLS:C0020538_hypertensive disease   
11                 UMLS:C0020538_hypertensive disease   
12                             UMLS:C0011847_diabetes   
13                             UMLS:C0011847_diabetes   
14                             UMLS:C0011847_diabetes   
15                             UMLS:C0011847_diabetes   
16                             UMLS:C0011847_diabetes   
17                             UMLS:C0011847_diabetes   
18                             UMLS:C0011847_diabetes   
19                             UMLS:C0011847_diabetes   
20                             UMLS:C0011847_diabetes   
21                             UMLS:C0011847_diabetes   
22                             UMLS:C0011847_diabetes   
23                             UMLS:C0011847_diabetes   
24                             UMLS:C0011847_diabetes   
25                             UMLS:C0011847_diabetes   
26  UMLS:C0011570_depression mental^UMLS:C0011581_...   
27  UMLS:C0011570_depression mental^UMLS:C0011581_...   
28  UMLS:C0011570_depression mental^UMLS:C0011581_...   
29  UMLS:C0011570_depression mental^UMLS:C0011581_...   

    Count of Disease Occurrence  \
0                        3363.0   
1                        3363.0   
2                        3363.0   
3                        3363.0   
4                        3363.0   
5                        3363.0   
6                        3363.0   
7                        3363.0   
8                        3363.0   
9                        3363.0   
10                       3363.0   
11                       3363.0   
12                       1421.0   
13                       1421.0   
14                       1421.0   
15                       1421.0   
16                       1421.0   
17                       1421.0   
18                       1421.0   
19                       1421.0   
20                       1421.0   
21                       1421.0   
22                       1421.0   
23                       1421.0   
24                       1421.0   
25                       1421.0   
26                       1337.0   
27                       1337.0   
28                       1337.0   
29                       1337.0   

                                              Symptom  
0                            UMLS:C0008031_pain chest  
1                   UMLS:C0392680_shortness of breath  
2                             UMLS:C0012833_dizziness  
3                              UMLS:C0004093_asthenia  
4                                  UMLS:C0085639_fall  
5                               UMLS:C0039070_syncope  
6                               UMLS:C0042571_vertigo  
7   UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...  
8                           UMLS:C0030252_palpitation  
9                                UMLS:C0027497_nausea  
10                      UMLS:C0002962_angina pectoris  
11                       UMLS:C0438716_pressure chest  
12                             UMLS:C0032617_polyuria  
13                           UMLS:C0085602_polydypsia  
14                  UMLS:C0392680_shortness of breath  
15                           UMLS:C0008031_pain chest  
16                             UMLS:C0004093_asthenia  
17                               UMLS:C0027497_nausea  
18                            UMLS:C0085619_orthopnea  
19                                 UMLS:C0034642_rale  
20  UMLS:C003899

In [10]:
# Xử lý tên bệnh và triệu chứng
def process_data(data):
    data_list = []
    data_name = data.replace('^','_').split('_')
    n = 1
    for names in data_name:
        if (n % 2 == 0):
            data_list.append(names)
        n += 1
    return data_list

In [12]:
# Dọn dẹp dữ liệu
disease_list = []
disease_symptom_dict = defaultdict(list)
disease_symptom_count = {}
count = 0

for idx, row in data.iterrows():

        # Lấy tên bệnh
    if (row['Disease'] !="\xc2\xa0") and (row['Disease'] != ""):
        disease = row['Disease']
        disease_list = process_data(data=disease)
        count = row['Count of Disease Occurrence']

 # Lấy triệu chứng tương ứng với bệnh
    if (row['Symptom'] !="\xc2\xa0") and (row['Symptom'] != ""):
        symptom = row['Symptom']
        symptom_list = process_data(data=symptom)
        for d in disease_list:
            for s in symptom_list:
                disease_symptom_dict[d].append(s)
            disease_symptom_count[d] = count

In [13]:
# Kiểm tra dữ liệu đã được xử lý đúng CHƯA
disease_symptom_dict

defaultdict(list,
            {'hypertensive disease': ['pain chest',
              'shortness of breath',
              'dizziness',
              'asthenia',
              'fall',
              'syncope',
              'vertigo',
              'sweat',
              'sweating increased',
              'palpitation',
              'nausea',
              'angina pectoris',
              'pressure chest'],
             'diabetes': ['polyuria',
              'polydypsia',
              'shortness of breath',
              'pain chest',
              'asthenia',
              'nausea',
              'orthopnea',
              'rale',
              'sweat',
              'sweating increased',
              'unresponsiveness',
              'mental status changes',
              'vertigo',
              'vomiting',
              'labored breathing'],
             'depression mental': ['feeling suicidal',
              'suicidal',
              'hallucinations auditory',
              'feel

In [14]:
# Đếm số lần xuất hiện của biểu hiện bệnh tương ứng với từng bệnh
disease_symptom_count

{'hypertensive disease': 3363.0,
 'diabetes': 1421.0,
 'depression mental': 1337.0,
 'depressive disorder': 1337.0,
 'coronary arteriosclerosis': 1284.0,
 'coronary heart disease': 1284.0,
 'pneumonia': 1029.0,
 'failure heart congestive': 963.0,
 'accident\xa0cerebrovascular': 885.0,
 'asthma': 835.0,
 'myocardial infarction': 759.0,
 'hypercholesterolemia': 685.0,
 'infection': 630.0,
 'infection urinary tract': 597.0,
 'anemia': 544.0,
 'chronic obstructive airway disease': 524.0,
 'dementia': 504.0,
 'insufficiency renal': 445.0,
 'confusion': 408.0,
 'degenerative\xa0polyarthritis': 405.0,
 'hypothyroidism': 398.0,
 'anxiety state': 390.0,
 'malignant neoplasms': 354.0,
 'primary malignant neoplasm': 354.0,
 'acquired\xa0immuno-deficiency syndrome': 350.0,
 'HIV': 350.0,
 'hiv infections': 350.0,
 'cellulitis': 341.0,
 'gastroesophageal reflux disease': 325.0,
 'septicemia': 311.0,
 'systemic infection': 311.0,
 'sepsis (invertebrate)': 311.0,
 'deep vein thrombosis': 310.0,
 'deh

In [17]:
# Lưu dữ liệu đã dọn dẹp vào file CSV
f = open('/content/drive/My Drive/Colab Notebooks/Check-check-test-test/dataset/cleaned_data.csv', 'w')

with f:
    writer = csv.writer(f)
    for key, val in disease_symptom_dict.items():
        for i in range(len(val)):
            writer.writerow([key, val[i], disease_symptom_count[key]])

In [19]:
# Đọc dữ liệu đã dọn dẹp dưới dạng DataFrame
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Check-check-test-test/dataset/cleaned_data.csv')
df.columns = ['disease', 'symptom', 'occurence_count']
df.head(30)

disease                  symptom  occurence_count
0   hypertensive disease      shortness of breath           3363.0
1   hypertensive disease                dizziness           3363.0
2   hypertensive disease                 asthenia           3363.0
3   hypertensive disease                     fall           3363.0
4   hypertensive disease                  syncope           3363.0
5   hypertensive disease                  vertigo           3363.0
6   hypertensive disease                    sweat           3363.0
7   hypertensive disease       sweating increased           3363.0
8   hypertensive disease              palpitation           3363.0
9   hypertensive disease                   nausea           3363.0
10  hypertensive disease          angina pectoris           3363.0
11  hypertensive disease           pressure chest           3363.0
12              diabetes                 polyuria           1421.0
13              diabetes               polydypsia           1421.0
14              diabetes      shortness of breath           1421.0
15              diabetes               pain chest           1421.0
16              diabetes                 asthenia           1421.0
17              diabetes                   nausea           1421.0
18              diabetes                orthopnea           1421.0
19              diabetes                     rale           1421.0
20              diabetes                    sweat           1421.0
21              diabetes       sweating increased           1421.0
22              diabetes         unresponsiveness           1421.0
23              diabetes    mental status changes           1421.0
24              diabetes                  vertigo           1421.0
25              diabetes                 vomiting           1421.0
26              diabetes        labored breathing           1421.0
27     depression mental         feeling suicidal           1337.0
28     depression mental                 suicidal           1337.0
29     depression mental  hallucinations auditory           1337.0

In [ ]:
df.tail(10)

In [20]:
# Loại bỏ bất kỳ hàng nào có giá trị trống - TIẾP THEO
df.replace(float('nan'), np.nan, inplace=True)
df.dropna(inplace=True)

In [21]:
from sklearn import preprocessing

In [22]:
n_unique = len(df['symptom'].unique())
n_unique

404

In [23]:
df.dtypes

disease             object
symptom             object
occurence_count    float64
dtype: object

In [ ]:
# Mã hóa nhãn thành số
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(df['symptom'])
print(integer_encoded)

[328  87  28 ... 361 130 122]


In [ ]:
# One Hot Encode nhãn
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
onehot_encoded[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
len(onehot_encoded[0])

404

In [ ]:
cols = np.asarray(df['symptom'].unique())
cols

array(['shortness of breath', 'dizziness', 'asthenia', 'fall', 'syncope',
       'vertigo', 'sweat', 'sweating increased', 'palpitation', 'nausea',
       'angina pectoris', 'pressure chest', 'polyuria', 'polydypsia',
       'pain chest', 'orthopnea', 'rale', 'unresponsiveness',
       'mental status changes', 'vomiting', 'labored breathing',
       'feeling suicidal', 'suicidal', 'hallucinations auditory',
       'feeling hopeless', 'weepiness', 'sleeplessness',
       'motor retardation', 'irritable mood', 'blackout',
       'mood depressed', 'hallucinations visual', 'worry', 'agitation',
       'tremor', 'intoxication', 'verbal auditory hallucinations',
       'energy increased', 'difficulty', 'nightmare',
       'unable to concentrate', 'homelessness', 'hypokinesia',
       'dyspnea on exertion', 'chest tightness', 'cough', 'fever',
       'decreased translucency', 'productive cough', 'pleuritic pain',
       'yellow sputum', 'breath sounds decreased', 'chill', 'rhonchus',
       '

In [ ]:
# Tạo một DataFrame mới để lưu nhãn OHE
df_ohe = pd.DataFrame(columns = cols)
df_ohe.head()

Empty DataFrame
Columns: [shortness of breath, dizziness, asthenia, fall, syncope, vertigo, sweat, sweating increased, palpitation, nausea, angina pectoris, pressure chest, polyuria, polydypsia, pain chest, orthopnea, rale, unresponsiveness, mental status changes, vomiting, labored breathing, feeling suicidal, suicidal, hallucinations auditory, feeling hopeless, weepiness, sleeplessness, motor retardation, irritable mood, blackout, mood depressed, hallucinations visual, worry, agitation, tremor, intoxication, verbal auditory hallucinations, energy increased, difficulty, nightmare, unable to concentrate, homelessness, hypokinesia, dyspnea on exertion, chest tightness, cough, fever, decreased translucency, productive cough, pleuritic pain, yellow sputum, breath sounds decreased, chill, rhonchus, green sputum, non-productive cough, wheezing, haemoptysis, distress respiratory, tachypnea, malaise, night sweat, jugular venous distention, dyspnea, dysarthria, speech slurred, facial paresis, hemiplegia, seizure, numbness, symptom aggravating factors, st segment elevation, st segment depression, t wave inverted, presence of q wave, chest discomfort, bradycardia, pain, nonsmoker, erythema, hepatosplenomegaly, pruritus, diarrhea, abscess bacterial, swelling, apyrexial, dysuria, hematuria, renal angle tenderness, lethargy, hyponatremia, hemodynamically stable, difficulty passing urine, consciousness clear, guaiac positive, monoclonal, ecchymosis, tumor cell invasion, haemorrhage, pallor, ...]
Index: []

[0 rows x 404 columns]

In [ ]:
for i in range(len(onehot_encoded)):
    df_ohe.loc[i] = onehot_encoded[i]

In [ ]:

df_ohe.head()

shortness of breath  dizziness  asthenia  fall  syncope  vertigo  sweat  \
0                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   
1                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   
2                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   
3                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   
4                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   

   sweating increased  palpitation  nausea  ...  feces in rectum  prodrome  \
0                 0.0          0.0     0.0  ...              0.0       0.0   
1                 0.0          0.0     0.0  ...              0.0       0.0   
2                 0.0          0.0     0.0  ...              0.0       0.0   
3                 0.0          0.0     0.0  ...              0.0       0.0   
4                 0.0          0.0     0.0  ...              0.0       0.0   

   hypoproteinemia  alcohol binge episode  abdomen acute  air fluid level  \
0              0.0                    0.0            0.0              0.0   
1              0.0                    0.0            0.0              0.0   
2              0.0                    0.0            0.0              0.0   
3              0.0                    0.0            0.0              0.0   
4              0.0                    0.0            0.0              0.0   

   catching breath  large-for-dates fetus  immobile  homicidal thoughts  
0              0.0                    0.0       0.0                 0.0  
1              0.0                    0.0       0.0                 0.0  
2              0.0                    0.0       0.0                 0.0  
3              0.0                    0.0       0.0                 0.0  
4              0.0                    0.0       0.0                 0.0  

[5 rows x 404 columns]

In [ ]:
len(df_ohe)

2126

In [ ]:
# DataFrame chứa tên bệnh
df_disease = df['disease']
df_disease.head()

0    hypertensive disease
1    hypertensive disease
2    hypertensive disease
3    hypertensive disease
4    hypertensive disease
Name: disease, dtype: object

In [ ]:
# Kết hợp nhãn OHE với cột bệnh
df_concat = pd.concat([df_disease,df_ohe], axis=1)
df_concat.head()

disease  shortness of breath  dizziness  asthenia  fall  \
0  hypertensive disease                  0.0        0.0       0.0   0.0   
1  hypertensive disease                  0.0        0.0       0.0   0.0   
2  hypertensive disease                  0.0        0.0       0.0   0.0   
3  hypertensive disease                  0.0        0.0       0.0   0.0   
4  hypertensive disease                  0.0        0.0       0.0   0.0   

   syncope  vertigo  sweat  sweating increased  palpitation  ...  \
0      0.0      0.0    0.0                 0.0          0.0  ...   
1      0.0      0.0    0.0                 0.0          0.0  ...   
2      0.0      0.0    0.0                 0.0          0.0  ...   
3      0.0      0.0    0.0                 0.0          0.0  ...   
4      0.0      0.0    0.0                 0.0          0.0  ...   

   feces in rectum  prodrome  hypoproteinemia  alcohol binge episode  \
0              0.0       0.0              0.0                    0.0   
1              0.0       0.0              0.0                    0.0   
2              0.0       0.0              0.0                    0.0   
3              0.0       0.0              0.0                    0.0   
4              0.0       0.0              0.0                    0.0   

   abdomen acute  air fluid level  catching breath  large-for-dates fetus  \
0            0.0              0.0              0.0                    0.0   
1            0.0              0.0              0.0                    0.0   
2            0.0              0.0              0.0                    0.0   
3            0.0              0.0              0.0                    0.0   
4            0.0              0.0              0.0                    0.0   

   immobile  homicidal thoughts  
0       0.0                 0.0  
1       0.0                 0.0  
2       0.0                 0.0  
3       0.0                 0.0  
4       0.0                 0.0  

[5 rows x 405 columns]

In [ ]:
df_concat.drop_duplicates(keep='first',inplace=True)

In [ ]:
df_concat.head()

disease  shortness of breath  dizziness  asthenia  fall  \
0  hypertensive disease                  0.0        0.0       0.0   0.0   
1  hypertensive disease                  0.0        0.0       0.0   0.0   
2  hypertensive disease                  0.0        0.0       0.0   0.0   
3  hypertensive disease                  0.0        0.0       0.0   0.0   
4  hypertensive disease                  0.0        0.0       0.0   0.0   

   syncope  vertigo  sweat  sweating increased  palpitation  ...  \
0      0.0      0.0    0.0                 0.0          0.0  ...   
1      0.0      0.0    0.0                 0.0          0.0  ...   
2      0.0      0.0    0.0                 0.0          0.0  ...   
3      0.0      0.0    0.0                 0.0          0.0  ...   
4      0.0      0.0    0.0                 0.0          0.0  ...   

   feces in rectum  prodrome  hypoproteinemia  alcohol binge episode  \
0              0.0       0.0              0.0                    0.0   
1              0.0       0.0              0.0                    0.0   
2              0.0       0.0              0.0                    0.0   
3              0.0       0.0              0.0                    0.0   
4              0.0       0.0              0.0                    0.0   

   abdomen acute  air fluid level  catching breath  large-for-dates fetus  \
0            0.0              0.0              0.0                    0.0   
1            0.0              0.0              0.0                    0.0   
2            0.0              0.0              0.0                    0.0   
3            0.0              0.0              0.0                    0.0   
4            0.0              0.0              0.0                    0.0   

   immobile  homicidal thoughts  
0       0.0                 0.0  
1       0.0                 0.0  
2       0.0                 0.0  
3       0.0                 0.0  
4       0.0                 0.0  

[5 rows x 405 columns]

In [ ]:
len(df_concat)

2097

In [ ]:
cols = df_concat.columns
cols

Index(['disease', 'shortness of breath', 'dizziness', 'asthenia', 'fall',
       'syncope', 'vertigo', 'sweat', 'sweating increased', 'palpitation',
       ...
       'feces in rectum', 'prodrome', 'hypoproteinemia',
       'alcohol binge episode', 'abdomen acute', 'air fluid level',
       'catching breath', 'large-for-dates fetus', 'immobile',
       'homicidal thoughts'],
      dtype='object', length=405)

In [ ]:
cols = cols[1:]

In [ ]:
# Vì mỗi bệnh có nhiều triệu chứng, gộp tất cả triệu chứng cho mỗi bệnh trong mỗi hàng
df_concat = df_concat.groupby('disease').sum()
df_concat = df_concat.reset_index()
df_concat[:5]

disease  shortness of breath  dizziness  \
0                  Alzheimer's disease                  0.0        0.0   
1                                  HIV                  0.0        0.0   
2       Pneumocystis carinii pneumonia                  0.0        0.0   
3             accident cerebrovascular                  0.0        0.0   
4  acquired immuno-deficiency syndrome                  0.0        0.0   

   asthenia  fall  syncope  vertigo  sweat  sweating increased  palpitation  \
0       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
1       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
2       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
3       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
4       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   

   ...  feces in rectum  prodrome  hypoproteinemia  alcohol binge episode  \
0  ...              0.0       0.0              0.0                    0.0   
1  ...              0.0       0.0              0.0                    0.0   
2  ...              0.0       0.0              0.0                    0.0   
3  ...              0.0       0.0              0.0                    0.0   
4  ...              0.0       0.0              0.0                    0.0   

   abdomen acute  air fluid level  catching breath  large-for-dates fetus  \
0            0.0              1.0              0.0                    0.0   
1            0.0              0.0              0.0                    0.0   
2            0.0              0.0              0.0                    0.0   
3            0.0              0.0              0.0                    0.0   
4            0.0              0.0              0.0                    0.0   

   immobile  homicidal thoughts  
0       0.0                 0.0  
1       0.0                 0.0  
2       0.0                 1.0  
3       0.0                 0.0  
4       0.0                 0.0  

[5 rows x 405 columns]

In [ ]:
len(df_concat)

149

In [ ]:
# Lưu dữ liệu đã xủ lí lặp - sạch lại
df_concat.to_csv("/content/drive/My Drive/Colab Notebooks/dataset/training_dataset.csv", index=False)

In [ ]:
df_concat

disease  shortness of breath  dizziness  \
0                    Alzheimer's disease                  0.0        0.0   
1                                    HIV                  0.0        0.0   
2         Pneumocystis carinii pneumonia                  0.0        0.0   
3               accident cerebrovascular                  0.0        0.0   
4    acquired immuno-deficiency syndrome                  0.0        0.0   
..                                   ...                  ...        ...   
144                tonic-clonic seizures                  0.0        0.0   
145            transient ischemic attack                  0.0        0.0   
146        tricuspid valve insufficiency                  0.0        0.0   
147                         ulcer peptic                  0.0        0.0   
148          upper respiratory infection                  0.0        0.0   

     asthenia  fall  syncope  vertigo  sweat  sweating increased  palpitation  \
0         0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
1         0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
2         0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
3         0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
4         0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
..        ...   ...      ...      ...    ...                 ...          ...   
144       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
145       1.0   0.0      0.0      0.0    0.0                 0.0          0.0   
146       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
147       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
148       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   

     ...  feces in rectum  prodrome  hypoproteinemia  alcohol binge episode  \
0    ...              0.0       0.0              0.0                    0.0   
1    ...              0.0       0.0              0.0                    0.0   
2    ...              0.0       0.0              0.0                    0.0   
3    ...              0.0       0.0              0.0                    0.0   
4    ...              0.0       0.0              0.0                    0.0   
..   ...              ...       ...              ...                    ...   
144  ...              0.0       0.0              0.0                    0.0   
145  ...              1.0       0.0              0.0                    0.0   
146  ...              0.0       0.0              0.0                    0.0   
147  ...              0.0       1.0              0.0                    0.0   
148  ...              0.0       0.0              0.0                    0.0   

     abdomen acute  air fluid level  catching breath  large-for-dates fetus  \
0              0.0              1.0              0.0                    0.0   
1              0.0              0.0              0.0                    0.0   
2              0.0              0.0              0.0                    0.0   
3              0.0              0.0              0.0                    0.0   
4              0.0              0.0              0.0                    0.0   
..             ...              ...              ...                    ...   
144            0.0              0.0              0.0                    0.0   
145            0.0              0.0              0.0                    0.0   
146            0.0              0.0              0.0                    0.0   
147            0.0              0.0              0.0                    0.0   
148            0.0              0.0              0.0                    0.0   

     immobile  homicidal thoughts  
0         0.0                 0.0  
1         0.0                 0.0  
2         0.0                 1.0  
3         0.0                 0.0  
4         0.0                 0.0  
..        ...                 ...

In [ ]:
# Các đặc trưng được mã hóa One Hot
X = df_concat[cols]

# Nhãn
y = df_concat['disease']

## Model Training

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [ ]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [ ]:
len(X_train), len(y_train)

(119, 119)

In [ ]:
len(X_test), len(y_test)

(30, 30)

In [ ]:
dt = DecisionTreeClassifier()
clf_dt=dt.fit(X, y)

In [ ]:
clf_dt.score(X, y)

0.9731543624161074

In [ ]:
export_graphviz(dt,
                out_file='./tree.dot',
                feature_names=cols)

In [ ]:
!pip install graphviz

In [ ]:
from graphviz import Source
from sklearn import tree

graph = Source(export_graphviz(dt,
                out_file=None,
                feature_names=cols))

png_bytes = graph.pipe(format='png')

with open('tree.png','wb') as f:
    f.write(png_bytes)

In [ ]:
from IPython.display import Image
Image(png_bytes)

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
disease_pred = clf_dt.predict(X)

In [ ]:
disease_real = y.values

In [ ]:
for i in range(0, len(disease_real)):
    if disease_pred[i]!=disease_real[i]:
        print ('Pred: {0}\nActual: {1}\n'.format(disease_pred[i], disease_real[i]))

Pred: coronary arteriosclerosis
Actual: coronary heart disease

Pred: depression mental
Actual: depressive disorder

Pred: malignant neoplasms
Actual: primary malignant neoplasm

Pred: septicemia
Actual: systemic infection

